### ISSUE TITLE
getRedirectionURL is not applied to the thirdparty recipe properly?

### ISSUE THREAD

**Issue by flixoflax** [supertokens/supertokens-auth-react#560] opened 2022-08-16 13:04 UTC
Hi! I am trying to develop my custom UI with Supertokens, and it seems that everything is working correctly. Except one thing... My signup/signin flow works like this: First a user signs up using email/password or social signinup then the frontend redirects it to a set-username route where the user has to set a username and then an email verification link is send. I have overwritten the following functions: `doesSessionExist` and `getRedirectionPath`. It works like a charm with email and password, and also with the Facebook Provider. However, it doesn't seem to work with the Google Provider. Every time I try to sign in or up with the Google provider, I get redirected to my dashboard, not the set-username route. If I refresh the page Supertokens instantly remembers that there shouldn't be a session and redirects me to the set-username route  (The only difference I see is that you do not need to verify the Google email address, while you need to verify the Facebook email, which should be handled by a logic in the `doesSessionExist `where we first check the atp and then check the email). Seems like a strange thing to me...

This is my config:
```
import ThirdPartyEmailPassword, {
  Google,
  Facebook,
} from 'supertokens-auth-react/recipe/thirdpartyemailpassword'
import Session from 'supertokens-auth-react/recipe/session'
import { SuperTokensConfig } from 'supertokens-auth-react/lib/build/types'
import NextRouter from 'next/router'
import { store } from './store'
import authApi from './api/auth'

const supertokensConfig: () => SuperTokensConfig = () => ({
  appInfo: {
    // learn more about this on https://supertokens.com/docs/thirdpartyemailpassword/appinfo
    appName: process.env.NEXT_PUBLIC_SUPERTOKENS_APP_NAME as string,
    apiDomain: process.env.NEXT_PUBLIC_SUPERTOKENS_API_DOMAIN as string,
    websiteDomain: process.env.NEXT_PUBLIC_SUPERTOKENS_WEB_DOMAIN as string,
    apiBasePath: process.env.NEXT_PUBLIC_SUPERTOKENS_API_BASE_PATH,
    websiteBasePath: process.env.NEXT_PUBLIC_SUPERTOKENS_WEB_BASE_PATH,
  },
  recipeList: [
    ThirdPartyEmailPassword.init({
      override: {
        functions: (oI) => ({
          ...oI,
          async emailPasswordSignIn(input) {
            window.localStorage.removeItem('isEmailverified')
            return oI.emailPasswordSignIn(input)
          },
          async emailPasswordSignUp(input) {
            window.localStorage.removeItem('isEmailverified')
            return oI.emailPasswordSignUp(input)
          },
          async thirdPartySignInAndUp(input) {
            window.localStorage.removeItem('isEmailverified')
            return oI.thirdPartySignInAndUp(input)
          },
        }),
        emailVerification: {
          functions: (oI) => ({
            ...oI,
            async isEmailVerified(input) {
              const fromLocalstorage =
                window.localStorage.getItem('isEmailverified')
              if (fromLocalstorage == null) {
                const fromAPI = await oI.isEmailVerified(input)
                if (fromAPI.isVerified) {
                  window.localStorage.setItem('isEmailverified', 'true')
                }
                return fromAPI
              }
              return {
                fetchResponse: new Response(),
                isVerified: fromLocalstorage === 'true',
                status: 'OK',
              }
            },
          }),
        },
      },
      signInAndUpFeature: {
        providers: [Google.init(), Facebook.init()],
      },
      emailVerificationFeature: {
        mode: 'REQUIRED',
      },
      getRedirectionURL: async (context) => {
        if (context.action === 'SUCCESS') {
          // this is called after sign up / in and after email is verified
          const accessTokenPayload =
            await Session.getAccessTokenPayloadSecurely()
          if (accessTokenPayload.isUsernameSet === false) {
            return '/auth/set-username' // we ask the user to set their password now
          }

          const isEmailVerified =
            await ThirdPartyEmailPassword.isEmailVerified()

          if (!isEmailVerified.isVerified) {
            return '/auth/verify-email'
          }

          return '/'
        }

        try {
          const atp = await Session.getAccessTokenPayloadSecurely()
          if (atp.isUsernameSet === false) {
            return '/auth/set-username'
          }

          const isEmailVerified =
            await ThirdPartyEmailPassword.isEmailVerified()
          if (!isEmailVerified.isVerified) {
            return '/auth/verify-email'
          }
        } catch (error) {
          return undefined
        }

        return undefined
      },
      onHandleEvent: async (context) => {
        if (context.action === 'SUCCESS') {
          if (context.isNewUser) {
            // Set store
            store.setState({
              user: {
                id: context.user.id,
                email: context.user.email,
                username: undefined,
              },
            })

            // Send Email Verification Mail
            authApi.sendVerificationMail()
          } else {
            const atp = await Session.getAccessTokenPayloadSecurely()

            // Set store
            store.setState({
              user: {
                id: context.user.id,
                email: context.user.email,
                username: atp.username,
              },
            })
          }
        }
      },
    }),
    Session.init({
      override: {
        functions: (oI) => ({
          ...oI,
          async doesSessionExist(input) {
            if (!(await oI.doesSessionExist(input))) {
              return false
            }

            const accessTokenPayload = await this.getAccessTokenPayloadSecurely(
              input
            )

            if (accessTokenPayload.isUsernameSet === false) {
              return false
            }

            const emailVerified =
              await ThirdPartyEmailPassword.isEmailVerified()

            return emailVerified.isVerified
          },
        }),
      },
    }),
  ],
  windowHandler: (oI) => ({
    ...oI,
    location: {
      ...oI.location,
      setHref: (href) => {
        NextRouter.replace(href)
      },
    },
  }),
})

export default supertokensConfig

```

We (@rishabhpoddar @porcellus and myself) investigated further via discord, and it seems like there is a problem with the call order of the overwritten functions when signing in or up with Google. The procedure looks like this:  `doesSessionExist` (oI returns false) - `onHandleEvent` (context.action is success and its a newUser) - `isEmailVerified` - `getRedirectionURL` (only for facebook).

The problem seems lies in the last function `getRedirectionURL` not being called when signing in or up with Google. 

I added both of you to the project.

**Comment by porcellus** [comment] 2022-08-16 20:44
I've checked out why/how things work in your app:
- You never get a success redirection; that only happens if you use our pre-built UI components.
- Your `doesSessionExist` override is only called during full-page reloads. If we create/refresh a session, we set the value to true in the context while handling the event without calling `doesSessionExist`. This explains why it "remembers" that it's not supposed to have a session after a refresh.
- `getRedirectionPath` is only called in your app by the `ThirdPartyEmailPasswordAuth`, if it detects that the user has no session or is missing email verification. Since you always have a session after sign-in, it explains the issue with third-party providers that mark the email address as verified.

My recommendation:
Replace `ThirdPartyEmailPasswordAuth` with your own component that uses `useSessionContext` and does the email verification, user name, and session checking and handles redirects. This way, you can remove the `getRedirectionURL`, and `doesSessionExist` overrides, which should be a bit cleaner in general.

**Comment by rishabhpoddar** [comment] 2022-08-17 06:34
Closing this issue since it's not a bug with the SDK.

**Closed by rishabhpoddar** 2022-08-17 06:34 UTC
