### ISSUE TITLE
sessionContext not destroyed on frontend after signOut in v.0.32.3

### ISSUE THREAD

**Issue by antoniodinovi** [supertokens/supertokens-auth-react#703] opened 2023-05-30 08:46 UTC
I'm using `supertokens-auth-react` in a `nextjs` application (v.13.4.4) and i'm using the signOut method to logout from my application.

```  
import { signIn, signOut } from 'supertokens-auth-react/recipe/emailpassword';
.....
const logout = async () => await signOut();
```

Using version `0.32.1` of `supertokens-auth-react` after logout session was detroyed both in frontend and backend sides of my application.

After upgrading to `0.32.3` session was detroyed only in the backend part, but `sessionContext` on the frontend always return the session data

```
import { useSessionContext } from 'supertokens-auth-react/recipe/session';

let sessionContext = useSessionContext();
...
if (sessionContext.doesSessionExist) { // --> always return "true" after signOut()
    push('/');
 }
...
```

**Comment by nkshah2** [comment] 2023-05-31 03:59
Hi @antoniodinovi What backend SDK and version are you using?

**Comment by nkshah2** [comment] 2023-06-02 05:23
Hi,

Closing this since we havent heard back from you, feel free to re-open if the issue still persists

**Comment by cbadour** [comment] 2023-06-05 10:49
I'am having the same issue with 

Frontend:
> "supertokens-auth-react": "^0.32.3"

Backend
>   "supertokens-node": "^14.0.2",

Please any help ?

**Comment by cbadour** [comment] 2023-06-05 13:29
By simply using these two versions of the packages with a Next JS frontend project connected to Nest JS backend Project.
And Repeating the same scenario as @antoniodinovi

**Comment by cbadour** [comment] 2023-06-05 14:04
I tried it, still the same

**Comment by rishabhpoddar** [comment] 2023-06-06 06:06
Can you please share a demo app with the issue happening in it? We are unable to reproduce it.

**Comment by cbadour** [comment] 2023-06-06 12:48
From witch directory should the signOut function be called ? I 'am importing it from 

`import { signOut } from "supertokens-auth-react/recipe/session";`

**Comment by rishabhpoddar** [comment] 2023-06-06 13:07
You can call it from anywhere. For saving time, we will be unable to help you if you won't share some code that can reproduce this issue.

**Comment by rishabhpoddar** [comment] 2023-06-11 16:33
Closing this issue cause no reply and we still can't reproduce it. But feel free to reopen

**Closed by rishabhpoddar** 2023-06-11 16:33 UTC

**Comment by cbadour** [comment] 2023-06-15 08:45
I found the Issue, When i start my Node JS backend locally on http://localhost:8003, i can normally sign out from my localhost Next JS front, but when i deployed my Backend on a server and connect to it i am not able to sign out anymore.

**Comment by cbadour** [comment] 2023-06-16 08:09
frontend appInfo:

`
appInfo = {
    appName: "simple-saas",
    apiDomain: "http://52.16.27.104:8003",
    websiteDomain: "http://localhost:3000",
    apiBasePath: "/auth",
    websiteBasePath: "/auth"
}
`

backend appInfo:

`
appInfo =  {
            appName: "simple-saas",
            apiDomain: "http://52.16.27.104:8003",
            websiteDomain: "http://localhost:3000",
            apiBasePath: "/auth",
            websiteBasePath: "/auth"
        }
`

Is there anything wrong with it ? it is the same

**Comment by rishabhpoddar** [comment] 2023-06-16 10:03
yea. this won't work with cookie based auth. Switch to using header based auth.

**Comment by cbadour** [comment] 2023-06-16 11:53
Okay this solution worked. But it is not recommended yes ? what should i do to fix it with cookie based auth ?

**Comment by rishabhpoddar** [comment] 2023-06-16 13:35
You would need to use the same base domain for website and api domain.

**Comment by cbadour** [comment] 2023-06-16 13:55
> yea. this won't work with cookie based auth. Switch to using header based auth.

/

**Comment by cbadour** [comment] 2023-06-16 13:55
> yea. this won't work with cookie based auth. Switch to using header based auth.

/
