### ISSUE TITLE
Overwrite component and use existing styles

### ISSUE THREAD

**Issue by jeremylynch** [supertokens/supertokens-auth-react#379] opened 2022-02-04 08:31 UTC
Is it possible to overwrite a component and import the existing emotion styles? See example below which I have attempted, this is not working. 

```js
/** @jsxImportSource @emotion/react */
import { jsx } from "@emotion/react";
import { Fragment, useContext } from "react";
import StyleContext from "supertokens-auth-react/lib/build/styles/styleContext";

export const UserInputCodeFormHeader = ({ loginAttemptInfo }) => {
  const styles = useContext(StyleContext);

  return (
    <Fragment>
        <div data-supertokens="headerTitle" css={styles.headerTitle}>
            Enter OTP
        </div>
        <div
            data-supertokens="headerSubtitle secondaryText"
            css={[styles.headerSubtitle, styles.secondaryText]}>
            {loginAttemptInfo.flowType === "USER_INPUT_CODE" ? "An OTP " : "An OTP and a magic link "} was sent
            to you at <br />
            <strong>{loginAttemptInfo.contactInfo}</strong>
        </div>
        <div data-supertokens="divider" css={styles.divider}></div>
    </Fragment>
  );
}
```

**Comment by rishabhpoddar** [comment] 2022-02-04 08:34
Thanks for making this issue @jeremylynch we will have a look. Until then, you can manually put in the styles for your custom component by inspecting them from the browser inspector.

**Comment by porcellus** [comment] 2022-02-04 10:53
Hi, I wasn't able to reproduce the issue it seems to be working for me here. See [here](https://codesandbox.io/s/lucid-fermat-e0iqm?file=/src/App.tsx). Could you please help us reproduce this? What did I do differently? The only thing I changed intentionally was that I added the override for `PasswordlessSignInHeader`

**Comment by porcellus** [comment] 2022-02-14 08:50
Should we close this issue and add a separate one for exporting (and using) `useStyleContext`?

**Comment by rishabhpoddar** [comment] 2022-02-14 09:53
@porcellus sure. Closing it now.

**Closed by rishabhpoddar** 2022-02-14 09:53 UTC
Labels: bug
