### ISSUE TITLE
Page is reloading with react-router-dom when I click on forgot password

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-auth-react#56] opened 2020-11-19 08:15 UTC
Please make sure this doesn't happen with any other navgiation as well.

**Comment by NkxxkN** [comment] 2020-11-19 08:47
I couldn't reproduce.
Here is what I did:
 - `cd ~/supertokens-demo-react`
 - `npm run build`
 - `npm run prod`
 - Go to `http://localhost:3000/` => `http://localhsot:3000/auth
 - Open console, remove preserve log checkbox
 - Click on Forgot Password
 - Redirected without reloading the page.
 - Logs are preserved which means the page was not reloaded.

https://www.loom.com/share/6096c33ea62b401dbfceca67c1b21963

Closing. Feel free to reopen with new repro steps if this still happens for you.

**Comment by rishabhpoddar** [comment] 2020-11-19 08:53
This bug exists. Reopening

**Comment by NkxxkN** [comment] 2020-11-19 08:54
Tried on 0.1 and it does happens.

**Closed** 2020-11-19 15:05 UTC
Labels: bug
